"""Created categories and item_groups table also alter table items

Revision ID: 0c1a1f452142
Revises: 372c1081e6aa
Create Date: 2026-09-13 09:01:46.133554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1a1f452142'
down_revision: Union[str, Sequence[str], None] = '372c1081e6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_categories_created_by_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_categories_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_categories_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_categories_tenant_id'))
    )
    op.create_index('ix_categories_tenant_id', 'categories', ['tenant_id'], unique=False)
    op.create_table('item_groups',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_item_groups_category_id_categories')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_item_groups_created_by_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_item_groups_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_item_groups_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_groups')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_item_groups_tenant_id'))
    )
    op.create_index('ix_item_groups_tenant_id', 'item_groups', ['tenant_id'], unique=False)
    op.add_column('items', sa.Column('is_available', sa.Boolean(), nullable=False))
    op.add_column('items', sa.Column('group_id', sa.Uuid(), nullable=False))
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.create_unique_constraint(op.f('uq_items_tenant_id'), 'items', ['tenant_id', 'name'])
    op.create_foreign_key(op.f('fk_items_group_id_item_groups'), 'items', 'item_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_items_group_id_item_groups'), 'items', type_='foreignkey')
    op.drop_constraint(op.f('uq_items_tenant_id'), 'items', type_='unique')
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('items', 'group_id')
    op.drop_column('items', 'is_available')
    op.drop_index('ix_item_groups_tenant_id', table_name='item_groups')
    op.drop_table('item_groups')
    op.drop_index('ix_categories_tenant_id', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
