"""Making user_tenants table created_by_id, tenant_id field nullable

Revision ID: 1eaf92c6f304
Revises: 42717a306533
Create Date: 2026-06-12 07:44:22.765121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eaf92c6f304'
down_revision: Union[str, Sequence[str], None] = '42717a306533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tenants', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tenants', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
