"""New field (is_system_role)  added to role table

Revision ID: 2b3666400e95
Revises: 1f3161317400
Create Date: 2026-06-11 13:54:37.164786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3666400e95'
down_revision: Union[str, Sequence[str], None] = '1f3161317400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_system_role', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_system_role')
    # ### end Alembic commands ###
