"""Removed tenant id from email change request table

Revision ID: 372c1081e6aa
Revises: ddc0f1a6cbb8
Create Date: 2026-09-06 13:09:33.070095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372c1081e6aa'
down_revision: Union[str, Sequence[str], None] = 'ddc0f1a6cbb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_email_change_requests_tenant_id_tenants'), 'email_change_requests', type_='foreignkey')
    op.drop_column('email_change_requests', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_change_requests', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_email_change_requests_tenant_id_tenants'), 'email_change_requests', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###
