"""Making user table created_by_id field nullable

Revision ID: 42717a306533
Revises: 2b3666400e95
Create Date: 2026-06-12 07:41:15.166747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42717a306533'
down_revision: Union[str, Sequence[str], None] = '2b3666400e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
