"""Create Table EmailChangeRequest And Add is_delete column in user table

Revision ID: 561a9459a753
Revises: 6542c59f50a8
Create Date: 2026-08-10 10:10:23.301478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561a9459a753'
down_revision: Union[str, Sequence[str], None] = '6542c59f50a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_change_requests',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('old_email', sa.String(), nullable=False),
    sa.Column('new_email', sa.String(), nullable=False),
    sa.Column('new_email_verification_token', sa.String(length=64), nullable=True),
    sa.Column('new_email_verification_token_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_email_change_requests_created_by_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_email_change_requests_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_email_change_requests_updated_by_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_change_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_change_requests'))
    )
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_table('email_change_requests')
    # ### end Alembic commands ###
