"""Removed is_super_admin_permission from permissions table

Revision ID: 6542c59f50a8
Revises: 97c9aa952abe
Create Date: 2026-06-22 05:37:25.658235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6542c59f50a8'
down_revision: Union[str, Sequence[str], None] = '97c9aa952abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'is_super_admin_permission')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('is_super_admin_permission', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
