"""Alter table petenants remove unique constraint and add is_deleted field

Revision ID: 97c9aa952abe
Revises: ec6024a67283
Create Date: 2026-06-16 05:13:29.661071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c9aa952abe'
down_revision: Union[str, Sequence[str], None] = 'ec6024a67283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('uq_tenants_code'), 'tenants', type_='unique')
    op.drop_constraint(op.f('uq_tenants_name'), 'tenants', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_tenants_name'), 'tenants', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_tenants_code'), 'tenants', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('tenants', 'is_deleted')
    # ### end Alembic commands ###
