"""Password reset field added to user table

Revision ID: ddc0f1a6cbb8
Revises: 561a9459a753
Create Date: 2026-08-25 07:50:30.725659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc0f1a6cbb8'
down_revision: Union[str, Sequence[str], None] = '561a9459a753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_password_verification_token', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('new_password_verification_token_created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new_password_verification_token_created_at')
    op.drop_column('users', 'new_password_verification_token')
    # ### end Alembic commands ###
